In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
%matplotlib inline
import math

In [2]:
credit = pd.read_csv("C:/Users/Bishwarup/Desktop/Analytix Labs/Analytix Labs(Case Study & Assignments)/Basic_Stats_1/creditpromo.csv")
diet = pd.read_csv("C:/Users/Bishwarup/Desktop/Analytix Labs/Analytix Labs(Case Study & Assignments)/Basic_Stats_1/dietstudy.csv")
pollination = pd.read_csv("C:/Users/Bishwarup/Desktop/Analytix Labs/Analytix Labs(Case Study & Assignments)/Basic_Stats_1/pollination.csv")
dvd = pd.read_csv("C:/Users/Bishwarup/Desktop/Analytix Labs/Analytix Labs(Case Study & Assignments)/Basic_Stats_1/dvdplayer.csv")
sample = pd.read_csv("C:/Users/Bishwarup/Desktop/Analytix Labs/Analytix Labs(Case Study & Assignments)/Basic_Stats_1/sample_survey.csv")
tolerance = pd.read_csv("C:/Users/Bishwarup/Desktop/Analytix Labs/Analytix Labs(Case Study & Assignments)/Basic_Stats_1/tolerance.csv")

In [3]:
#Q1. Weights and triglyceride levels are measured before and after the study.

In [4]:
#Comparing tg0 with tg4

stats.pearsonr(x = diet.tg0, y= diet.tg4)

# The triglyceride level has been slightly inversly proportional.

#Comparing wgt0 with wgt4
stats.pearsonr(x=diet.wgt0, y=diet.wgt4)

#The weights of the patients have been strongly directly proportional which is close to a perfect corelation.


(0.9962873971415401, 2.581375314291415e-16)

In [5]:
#We are checking if any measurements has changed.
#Both the measurements have changed with time.
#We have a positive coreelation which is linear in nature.
#The measurements are sightly directly proportional

diet.tg0.mean()
diet.wgt0.mean()

stats.pearsonr(x = diet.tg0, y= diet.wgt0)



(0.21887930415006523, 0.41539057707948285)

In [6]:
#We are checking if any measurements has changed.
#Both the measurements have changed with time.
#We have a positive coreelation which is linear in nature.
#The measurements are sightly directly proportional


stats.pearsonr(x = diet.tg1, y= diet.wgt1)


(0.10866232312018603, 0.6887284842583259)

In [7]:
#We are checking if any measurements has changed.
#Both the measurements have changed with time.
#We have a positive coreelation which is linear in nature.
#The measurements are sightly inversely proportional

stats.pearsonr(x = diet.tg2, y= diet.wgt2)


(-0.20852264301808981, 0.4383340440660211)

In [8]:
#We are checking if any measurements has changed.
#Both the measurements have changed with time.
#We have a positive coreelation which is linear in nature.
#The measurements are sightly to intermediate directly proportional



stats.pearsonr(x = diet.tg3, y= diet.wgt3)


(0.0428763781612011, 0.8747210405949991)

In [9]:
#We are checking if any measurements has changed.
#Both the measurements have changed with time.
#We have a negative coreelation which is linear in nature.
#The measurements are sightly to intermediate inversely proportional

stats.pearsonr(x = diet.tg4, y= diet.wgt4)

(-0.3541876843555759, 0.17831816012707075)

In [10]:
#Q2. 
#Subsetting the standard and new promotion ads.
s = credit[credit.loc[:,'insert']== 'Standard']
n = credit[credit.loc[:,'insert']== 'New Promotion']

In [11]:
credit

id         insert      dollars
0       148       Standard  2232.771979
1       572  New Promotion  1403.807542
2       973       Standard  2327.092181
3      1096       Standard  1280.030541
4      1541  New Promotion  1513.563200
..      ...            ...          ...
495  130163  New Promotion  1513.060134
496  130204  New Promotion  1020.757943
497  130255       Standard  1919.856304
498  130583       Standard  1863.014814
499  130682       Standard  1295.012183

[500 rows x 3 columns]

In [12]:
s.dollars.mean() #Mean of Standard seasonal ads

1566.3890309659348

In [13]:
n.dollars.mean() #Mean of New Promotion

1637.4999830647992

In [14]:
stats.ttest_rel(a = s.dollars,
               b = n.dollars)

#Relational T Test

#Corelation check by Pearson R

stats.pearsonr(s.dollars,n.dollars)


(0.028453871369634457, 0.654347192426946)

We can see the mean has increased after the new promotion meaning that the sales increased in that front. We can be 95% confident about the same.
Also, the relational T Test proves that we have a pvalue proving that the null hypothesis is valid.
Also, the values are corelated in a linear fashion.

The promotion is doing well in respect to the sales of the company as it has increased.




In [15]:
#Q3(a)
pollination.Seed_Yield_Plant.mean()

#stats.ttest_1samp(a = pollination.Seed_Yield_Plant,popmean = 180.80)

180.8035

The mean of the Seed Yield/Plant is less than 200.

In [16]:
#Q3(b) Filtering Natural and Hand Group for analysis
n = pollination[pollination.loc[:,'Group']== 'Natural'] #Natural Group
n.Seed_Yield_Plant

0    147.70
1    136.86
2    149.97
3    172.33
4    144.46
5    138.30
6    150.58
7    140.99
8    140.57
9    138.33
Name: Seed_Yield_Plant, dtype: float64

In [17]:
h = pollination[pollination.loc[:,'Group']== 'Hand'] # Hand
h.Seed_Yield_Plant

10    224.26
11    197.50
12    230.34
13    217.05
14    233.84
15    216.52
16    211.93
17    210.37
18    199.87
19    214.30
Name: Seed_Yield_Plant, dtype: float64

In [18]:
stats.f_oneway(n.Seed_Yield_Plant, h.Seed_Yield_Plant) #ANOVA Test for Fruit Weight

#Null Hypothesis is rejected. Variances of both groups are different.


F_onewayResult(statistic=194.83303662980398, pvalue=4.271481585484407e-11)

In [19]:
stats.ttest_rel(a = h.Fruit_Wt, b= n.Fruit_Wt) #T-Test Relational for Fruit Weight

Ttest_relResult(statistic=16.003484109505287, pvalue=6.420421224715851e-08)

In [20]:
stats.f_oneway(n.Seedling_length, h.Seedling_length) #ANOVA Test for Seedling Length


F_onewayResult(statistic=6.46293337115627, pvalue=0.020428817064110556)

In [21]:
stats.ttest_rel(a = h.Seedling_length, b= n.Seedling_length) #T-Test Relational for Seedling Length

Ttest_relResult(statistic=2.9765905136151303, pvalue=0.015535315669362245)

In [22]:
stats.pearsonr(h.Seed_Yield_Plant,n.Seed_Yield_Plant) #The values are directly proportional and related in a linear way.

(0.3117709406774874, 0.38051546240093814)

In [23]:
stats.pearsonr(h.Seedling_length, n.Seedling_length) #The values are directly proportional and related in a linear way.


(0.2844947751910154, 0.42563861992077123)

In [24]:
stats.pearsonr(n.Fruit_Wt, n.Seedling_length) #Weak Coreelation (Inversely Proportional) of Natural Fruit weight and Seedling Length

(-0.19042551777830258, 0.5982234700583844)

In [25]:
stats.pearsonr(n.Fruit_Wt, n.Seed_Yield_Plant) #Weak Coreelation (Directly Proportional) of Natural Fruit weight and Seedling Yield Plant

(0.3946617870619607, 0.2590459303858451)

In [26]:
stats.pearsonr(h.Fruit_Wt, h.Seed_Yield_Plant) #Weak Coreelation (Directly Proportional) of Hand Fruit weight and Seedling Yield Plant

(0.12244405766029798, 0.7361333289292354)

In [27]:
stats.pearsonr(h.Fruit_Wt, h.Seedling_length) #Weak Coreelation (Inversely Proportional) of Natural Fruit weight and Seedling Length

(-0.024200415419768473, 0.9470925842902166)

After all the tests, we conclude that the hand pollination gives us the higher Fruit_Wt, Seed_Yield_Plant and   Seedling_Length than natural pollination and all this data is directly proportional.
    
Seed Yield and Fruit weight are Directly Proportional for both the types of pollination.
Seedling Length and Fruit weight are weakly inversly Proportional for both the types of pollination.

We can be 95% confident about the same as from the pvalues.
 
 

In [28]:
#Q4 
dvd

agegroup   dvdscore
0   65 and over  38.454803
1         55-64  17.669677
2   65 and over  31.704307
3   65 and over  25.924460
4      Under 25  30.450007
..          ...        ...
63        45-54  46.567682
64  65 and over  23.999491
65     Under 25  24.994419
66  65 and over  33.538502
67        45-54  37.201829

[68 rows x 2 columns]

In [29]:
#Applying ANOVA for two and more ordinal categorical and continous variables.

s1 = dvd.dvdscore[dvd.agegroup=='Under 25']
s2 = dvd.dvdscore[dvd.agegroup=='25-34']
s3 = dvd.dvdscore[dvd.agegroup=='35-44']
s4 = dvd.dvdscore[dvd.agegroup=='45-54']
s5 = dvd.dvdscore[dvd.agegroup=='55-64']
s6 = dvd.dvdscore[dvd.agegroup=='65 and over']

#Filtering using loc
#dvd.dvdscore[dvd.loc[:,'agegroup']== 'Under 25']

In [30]:
stats.f_oneway(s1,s2,s3,s4,s5)

F_onewayResult(statistic=5.8441662635802984, pvalue=0.0006879000551723672)

After applying the ANOVA test, we find that the p value exists, which means that the null hypothesis is not rejected and we can be 95% confident that the variances of the groups are similar; age groups are similar to each other in dvdscore and can say that the age groups did not rate the dvdscore differently.

In [31]:
#Q5
sample

id            wrkstat        marital  childs   age  educ  paeduc  \
0        1  Working full time       Divorced     2.0  60.0  12.0    12.0   
1        2  Working part-time  Never married     0.0  27.0  17.0    20.0   
2        3  Working full time        Married     2.0  36.0  12.0    12.0   
3        4  Working full time  Never married     0.0  21.0  13.0     NaN   
4        5  Working full time  Never married     0.0  35.0  16.0     NaN   
...    ...                ...            ...     ...   ...   ...     ...   
2827  2828  Working full time        Married     2.0  73.0  14.0     8.0   
2828  2829  Working full time       Divorced     0.0  40.0  12.0    12.0   
2829  2830            Retired        Married     0.0  73.0   6.0     4.0   
2830  2831  Working full time  Never married     0.0  47.0  12.0    12.0   
2831  2832  Working part-time  Never married     0.0  20.0  10.0     NaN   

      maeduc  speduc          degree  ...        agecat childcat news1 news2  \
0       12.0     NaN     High school  ...      55 to 64      1-2    No    No   
1        NaN     NaN  Junior college  ...      25 to 34     None    No    No   
2       12.0    16.0     High school  ...      35 to 44      1-2    No    No   
3       12.0     NaN     High school  ...  Less than 25     None    No    No   
4       12.0     NaN        Bachelor  ...      35 to 44     None    No    No   
...      ...     ...             ...  ...           ...      ...   ...   ...   
2827    12.0    12.0  Junior college  ...   65 or older      1-2    No    No   
2828    12.0     NaN     High school  ...      35 to 44     None    No    No   
2829     NaN    10.0  LT High school  ...   65 or older     None   Yes    No   
2830    12.0     NaN     High school  ...      45 to 54     None    No    No   
2831     NaN     NaN  LT High school  ...  Less than 25     None    No    No   

      news3 news4 news5      car1      car2      car3  
0        No    No    No  American  Japanese  Japanese  
1       Yes    No    No  American    German  Japanese  
2        No   Yes   Yes  American  American       NaN  
3        No   Yes   Yes  American     Other       NaN  
4        No    No    No  American  American    Korean  
...     ...   ...   ...       ...       ...       ...  
2827     No    No    No  American  American    German  
2828     No    No    No  Japanese       NaN       NaN  
2829    Yes    No    No    Korean  American  American  
2830     No    No    No  Japanese       NaN       NaN  
2831     No    No    No   Swedish  American    German  

[2832 rows x 46 columns]

In [32]:
sample.info() #We have some null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2832 entries, 0 to 2831
Data columns (total 46 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   id        2832 non-null   int64  
 1   wrkstat   2831 non-null   object 
 2   marital   2831 non-null   object 
 3   childs    2825 non-null   float64
 4   age       2828 non-null   float64
 5   educ      2820 non-null   float64
 6   paeduc    2041 non-null   float64
 7   maeduc    2399 non-null   float64
 8   speduc    1311 non-null   float64
 9   degree    2822 non-null   object 
 10  sex       2832 non-null   object 
 11  race      2832 non-null   object 
 12  born      2819 non-null   object 
 13  parborn   2812 non-null   object 
 14  granborn  2630 non-null   float64
 15  income    2503 non-null   object 
 16  rincome   1849 non-null   object 
 17  polviews  2691 non-null   object 
 18  cappun    2599 non-null   object 
 19  postlife  2066 non-null   object 
 20  happy     2806 non-null   obje

In [33]:
#Q5.a
#Relation between labour force and martial status

sample.marital
sample.wrkstat

#If we need to check the relation between two categorical variables, we will use the chi-square method

0       Working full time
1       Working part-time
2       Working full time
3       Working full time
4       Working full time
              ...        
2827    Working full time
2828    Working full time
2829              Retired
2830    Working full time
2831    Working part-time
Name: wrkstat, Length: 2832, dtype: object

In [34]:
#CrossTab

a = pd.crosstab(index= sample.marital, columns = sample.wrkstat)
a

wrkstat        Keeping house  Other  Retired  School  Temporarily not working  \
marital                                                                         
Divorced                  25     12       53       7                        9   
Married                  200     16      168       9                       23   
Never married             35     14       17      60                       11   
Separated                 13      4        6       2                        1   
Widowed                   55      8      150       1                        2   

wrkstat        Unemployed, laid off  Working full time  Working part-time  
marital                                                                    
Divorced                         10                295                 35  
Married                          13                778                138  
Never married                    32                392                102  
Separated                         0                 58                  9  
Widowed                           3                 44                 20

In [35]:
#Chi square test for categorical variables


stats.chi2_contingency(observed = a)

(729.2421426572284,
 1.4875268409067568e-135,
 28,
 array([[ 51.69187279,   8.51024735,  62.09328622,  12.45017668,
           7.24946996,   9.14063604, 246.95477032,  47.90954064],
        [155.8869258 ,  25.66431095, 187.25441696,  37.5459364 ,
          21.86219081,  27.56537102, 744.74028269, 144.48056537],
        [ 76.84240283,  12.65088339,  92.30459364,  18.50777385,
          10.77667845,  13.58798587, 367.10989399,  71.21978799],
        [ 10.77879859,   1.7745583 ,  12.94770318,   2.59611307,
           1.51166078,   1.90600707,  51.495053  ,   9.99010601],
        [ 32.8       ,   5.4       ,  39.4       ,   7.9       ,
           4.6       ,   5.8       , 156.7       ,  30.4       ]]))

p value is very low so we will reject the null hypothesis.
As per the alternative hypothesis, They are dependent variables and directly corelate with each other categorically.
We can be 99% confident about the same.

In [36]:
#Q5 b. Educational qualification with marital status

sample.marital
sample.degree

#CrossTab
b = pd.crosstab(index = sample.marital, columns = sample.degree)
b
#

degree         Bachelor  Graduate  High school  Junior college  LT High school
marital                                                                       
Divorced             58        29          241              45              70
Married             251       123          686             108             174
Never married       129        41          367              46              77
Separated            12         3           58               3              17
Widowed              28         9          148               6              92

In [37]:
#Chi square test for categorical variables

stats.chi2_contingency(observed = b)

(122.68449020508541,
 1.6707923432360119e-18,
 16,
 array([[ 75.06345268,  32.19248493, 235.55476781,  32.66359447,
          67.52570011],
        [227.39312301,  97.52215526, 713.57674583,  98.94930876,
         204.55866714],
        [111.83268345,  47.9617157 , 350.9393832 ,  48.66359447,
         100.60262318],
        [ 15.75824176,   6.75824176,  49.45054945,   6.85714286,
          14.17582418],
        [ 47.95249911,  20.56540234, 150.4785537 ,  20.86635945,
          43.1371854 ]]))

p value is very low so we will reject the null hypothesis.
As per the alternative hypothesis, They are dependent variables and directly corelate with each other categorically.
Education qualification is indeed controlling the marital status.
We can be 99% confident about the same.

In [38]:
#Q5. (c)
#All three are ordinal categorical variables
sample.happy #Categorical
sample.marital #Categorical
sample.income # Categorical

0       $25000 or more
1       $15000 - 19999
2       $25000 or more
3       $15000 - 19999
4       $25000 or more
             ...      
2827    $20000 - 24999
2828    $15000 - 19999
2829    $20000 - 24999
2830    $25000 or more
2831    $25000 or more
Name: income, Length: 2832, dtype: object

In [39]:
#Checking the happiness with earnings

c = pd.crosstab(index = sample.happy, columns = sample.income)

In [40]:
#Chi-Square Test

stats.chi2_contingency(observed = c )

(178.9505306121643,
 1.4107677273473057e-26,
 22,
 array([[  3.89520355,  23.12777106,  21.66706973,  29.82265216,
         191.35187424,   2.92140266,   3.89520355,   4.26037888,
           4.01692866,   5.72108021,   7.06005643,   4.26037888],
        [ 18.16041919, 107.82748892, 101.01733172, 139.04070939,
         892.1305925 ,  13.62031439,  18.16041919,  19.86295848,
          18.72793229,  26.67311568,  32.91575977,  19.86295848],
        [  9.94437727,  59.04474002,  55.31559855,  76.13663845,
         488.51753325,   7.45828295,   9.94437727,  10.87666264,
          10.25513906,  14.60580411,  18.0241838 ,  10.87666264]]))

p value is very low so we will reject the null hypothesis.
As per the alternative hypothesis, They are dependent variables and directly corelate with each other categorically.
We are 99% confident about the testing.

In [41]:
#Checking the happiness with martial status

d = pd.crosstab(index = sample.happy, columns = sample.marital)
d

marital        Divorced  Married  Never married  Separated  Widowed
happy                                                              
Not too happy        72       71            108         30       59
Pretty happy        278      684            426         49      137
Very happy           93      582            120         13       83

In [42]:
#Chi-Square Test

stats.chi2_contingency(observed = d)

(260.6894389418282,
 9.3147261197964e-52,
 8,
 array([[ 53.6969697 , 162.06060606,  79.27272727,  11.15151515,
          33.81818182],
        [248.58538324, 750.24527629, 366.98609626,  51.62495544,
         156.55828877],
        [140.71764706, 424.69411765, 207.74117647,  29.22352941,
          88.62352941]]))

p value is very low so we will reject the null hypothesis. As per the alternative hypothesis, They are dependent variables and directly corelate with each other categorically. We are 99% confident about the testing.


Hence, happiness is driven with both martial status and earnings